"""expand_scan_model

Revision ID: 003bafdab750
Revises: add_auth_metadata
Create Date: 2026-07-12 06:28:51.558431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '003bafdab750'
down_revision: Union[str, None] = 'add_auth_metadata'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('original_filename', sa.String(), nullable=True))
    op.add_column('scans', sa.Column('stored_filename', sa.String(), nullable=True))
    op.add_column('scans', sa.Column('mime_type', sa.String(), nullable=True))
    op.add_column('scans', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('scans', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('scans', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('scans', sa.Column('storage_path', sa.String(), nullable=True))
    op.add_column('scans', sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('scans', sa.Column('started_processing_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('scans', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('scans', sa.Column('processing_time_ms', sa.Integer(), nullable=True))
    op.add_column('scans', sa.Column('error_message', sa.String(), nullable=True))
    op.add_column('scans', sa.Column('image_hash', sa.String(), nullable=True))
    op.add_column('scans', sa.Column('detected_objects', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('scans', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('scans', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_scans_image_hash'), 'scans', ['image_hash'], unique=False)
    op.create_index(op.f('ix_scans_stored_filename'), 'scans', ['stored_filename'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scans_stored_filename'), table_name='scans')
    op.drop_index(op.f('ix_scans_image_hash'), table_name='scans')
    op.alter_column('scans', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('scans', 'tags')
    op.drop_column('scans', 'detected_objects')
    op.drop_column('scans', 'image_hash')
    op.drop_column('scans', 'error_message')
    op.drop_column('scans', 'processing_time_ms')
    op.drop_column('scans', 'completed_at')
    op.drop_column('scans', 'started_processing_at')
    op.drop_column('scans', 'uploaded_at')
    op.drop_column('scans', 'storage_path')
    op.drop_column('scans', 'height')
    op.drop_column('scans', 'width')
    op.drop_column('scans', 'file_size')
    op.drop_column('scans', 'mime_type')
    op.drop_column('scans', 'stored_filename')
    op.drop_column('scans', 'original_filename')
    # ### end Alembic commands ###
